version: "3.5"
services:
        db:
                build: 
                        context: ./database/
                        dockerfile: Dockerfile
                restart: always
                container_name: db_container
                expose:
                        - "3306"
                deploy:
                        placement:
                                constraints:
                                        - node.role == manager
                volumes:
                        - type: volume
                          source: ../499_data/actual/
                          target: /var/lib/mysql/
                environment:
                        MYSQL_ROOT_PASSWORD: h_py_db2019@
                        MYSQL_DATABASE: HPOTDB19
                        MYSQL_USER: zfleharty
                        MYSQL_password: hpdb1996
        honeypy:
                build:
                        context: ./HoneyPy/
                        dockerfile: Dockerfile
                ports:
                        - "7:10007" #tcp/udp Echo
                        - "8:10008" #tcp/udp MOTD
                        - "2048:2048" #tcp Random
                        - "4096:4096" #tcp hashCountRandom
                entrypoint:
                        - python
                        - Honey.py
                        - -d
volumes:
  db_data:
        
