version: "3.5"
services:
        db:
                # Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
            - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: h_py_db2019@
      MYSQL_DATABASE: HPOTDB19
      MYSQL_USER: zfleharty
      MYSQL_password: hpdb1996

     
