version: '3.2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: h_py_db2019@
      MYSQL_DATABASE: HPOTDB19
      MYSQL_USER: zfleharty
      MYSQL_password: hpdb1996
