version: "3.5"
services:
  android:
    build:
      context: ./
      dockerfile: Dockerfile
    image: android:1.0
    restart: always
    container_name: Android2.2
    
  testing_container:
    image: ubuntu:latest
    container_name: testing
    
    
