version: "3.5"
services:
  android:
    build:
      context: ./
      dockerfile: Dockerfile_android
    image: android:1.0
    restart: always
    container_name: Android2.2
    entrypoint:
      - honeyd
      - -f
      - honeyd.conf
      - start
      
  testing_container:
    build:
      context: ./
      dockerfile: Dockerfile_testing
    image: testing_image
    container_name: testing_container
